Develop
KEA-ACCELER/alog-service-release pull request #1
Opened 2023-07-05 07:05 UTC by jipgago

CRUD 구현 완료 
Redis 구현시작

2023-07-05 08:29 UTC, vivi108 commented on Dockerfile
> +RUN java -jar lombok.jar install /alog-service-release
Why the command is needed? gradle package manager doesn't work?

2023-07-05 08:32 UTC, jipgago commented on Dockerfile
> +RUN java -jar lombok.jar install /alog-service-release
Other packages work well, but Lombok has not run.

2023-07-12 09:10 UTC, vivi108 requested changes

2023-07-12 09:10 UTC, vivi108 commented on src/main/java/kea/alog/release/config/RedisConfig.java
> +    private String host = "127.0.0.1";
let host be in docker-compose.yml, just like env.

2023-07-12 09:10 UTC, vivi108 commented on src/main/java/kea/alog/release/config/RedisConfig.java
> +    private int port = 6379;
let host be in docker-compose.yml, just like env. do not "hard-coding"

2023-07-12 09:10 UTC, vivi108 commented on src/main/java/kea/alog/release/service/TagService.java
> +    public TagPageingDTO getAllList(Long currentPage){
@Transactional is missing

2023-07-12 09:10 UTC, vivi108 commented on src/main/resources/application.yml
> +      host: 127.0.0.1
You've already define the port and host above, just like hard-coding-way
Why did you make env here also?
How about use @Value in code when you use envs?
And this should be define also in docker-compose.yml

2023-07-14 04:39 UTC, vivi108 approved these changes
LGTM

2023-07-14 04:40 UTC, merged